env:
- name: DB_NAME
  valueFrom:
    configMapKeyRef:
      name: postgresql-service
      key: DB_NAME
- name: DB_USER
  valueFrom:
    configMapKeyRef:
      name: postgresql-service
      key: DB_USER
- name: DB_HOST
  valueFrom:
    configMapKeyRef:
      name: postgresql-service
      key: DB_HOST
- name: DB_PORT
  valueFrom:
    configMapKeyRef:
      name: postgresql-service
      key: DB_PORT